# Generated by Django 6.0 on 2025-12-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorvariant',
            old_name='color',
            new_name='color_az',
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='color_en',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='color_ru',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colorvariant',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
