# Generated by Django 6.0 on 2025-12-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_color_colorvariant_color_az_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
