# Generated by Django 6.0 on 2026-01-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
